import { motion } from "framer-motion";
import { ShieldCheck, Zap, Download } from "lucide-react";

export default function Hero() {
  return (
    <section className="app-container pb-12 pt-14 md:pb-[72px] md:pt-24">
      <motion.div
        initial={{ opacity: 0, y: 24 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.7 }}
        className="max-w-4xl"
      >
        <p className="mb-4 inline-flex rounded-full border border-white/12 px-4 py-2 text-sm text-cyan">
          Fast online video splitter
        </p>
        <h1 className="mb-5 text-[36px] font-black leading-[1.1] md:text-5xl lg:text-[64px]">
          Split long videos into <span className="gradient-text">short clips</span> instantly
        </h1>
        <p className="mb-8 max-w-[680px] text-base leading-8 text-muted md:text-lg">
          Upload MP4, MOV, WEBM, or MKV files, choose 3 to 15 second clip duration, and download individual clips or a ZIP generated by native FFmpeg.
        </p>
        <div className="grid gap-3 text-sm text-muted sm:grid-cols-3">
          {[
            [Zap, "Fast native FFmpeg splitting"],
            [ShieldCheck, "Temporary server processing"],
            [Download, "Download clips or ZIP"]
          ].map(([Icon, label]) => (
            <div key={label} className="glass flex items-center gap-3 rounded-2xl p-4">
              <Icon className="text-cyan" size={20} aria-hidden="true" />
              <span>{label}</span>
            </div>
          ))}
        </div>
      </motion.div>
    </section>
  );
}
